### ISSUE TITLE
Expected stack map table for method with non-linear control flow.

### ISSUE THREAD

**Issue by michaellee123** [aleyn97/router#1]
打印大量重复日志，且耗时较长。

> Task :app:dexBuilderDebug

AGPBI: {"kind":"warning","text":"Expected stack map table for method with non-linear control flow.","sources":[{"file":"/Users/michaellee/StudioProjects/rv2/app/build/intermediates/classes/debug/ALL/debugLRouterHandleClasses/classes.jar"}],"tool":"D8"}//这一行日志估计打印了上千行

> Task :app:mergeDebugGlobalSynthetics UP-TO-DATE
> Task :app:processDebugJavaRes UP-TO-DATE
> Task :app:mergeDebugJavaResource
> Task :app:mergeDexDebug
> Task :app:packageDebug
> Task :app:createDebugApkListingFileRedirect UP-TO-DATE
> Task :app:assembleDebug

**Comment by aleyn97** [comment]
@michaellee123  你的 AGP 版本是多少呢

**Comment by michaellee123** [comment]
> 

8.1.0

**Comment by michaellee123** [comment]
> @michaellee123 你的 AGP 版本是多少呢

8.1.0 @aleyn97

**Comment by aleyn97** [comment]
> > @michaellee123 你的 AGP 版本是多少呢
> 
> 8.1.0 @aleyn97

目前并没发现插件的问题，这个警告是 R8 的检测。我接入几个的测试工程中，只有一个工程有这个警告。
原因好像是项目中依赖的某个第三方SDK的引起的。因为 LRouter 插件 会把所有类文件和引用到的库文件输出到一个 classes.jar 中。有问题的库也会抛警告到 最终生成classes.jar上。

你可以检查下你项目中有使用到哪些三方库或插件是否是他们引起的。

我后续会多关注这个警告。

**Comment by michaellee123** [comment]
> > > @michaellee123 你的 AGP 版本是多少呢
> > 
> > 
> > 8.1.0 @aleyn97
> 
> 目前并没发现插件的问题，这个警告是 R8 的检测。我接入几个的测试工程中，只有一个工程有这个警告。 原因好像是项目中依赖的某个第三方SDK的引起的。因为 LRouter 插件 会把所有类文件和引用到的库文件输出到一个 classes.jar 中。有问题的库也会抛警告到 最终生成classes.jar上。
> 
> 你可以检查下你项目中有使用到哪些三方库或插件是否是他们引起的。
> 
> 我后续会多关注这个警告。

感谢你的回复，这个问题导致我的编译时间增加了一倍，一直没能解决，我已经换回ARouter了
