### ISSUE TITLE
不支持fragment 跳转fragment 么？

### ISSUE THREAD

**Issue by qiushihang** [aleyn97/router#10]
我调用LRouter.build(xxx).navigation(), 却提示Acitivity 没有在AndroidManifest.xml

**Comment by qiushihang** [comment]
我主要是fragment跳转到另一个fragment，2个fragment都已经在路由表里注册，但是我看源码，Navigator.kt里goNavigator 是不是不支持fragment跳转？

**Comment by qiushihang** [comment]
LRouter.getFragment("/Main/Home")?.let {
            supportFragmentManager
                .beginTransaction()
                .replace(R.id.fl_content, it)
                .commitAllowingStateLoss()
        }

我看到了你的demo 里是这样跳的，是不支持像Arouter.build(xxxx).navigation()跳转对么

**Comment by aleyn97** [comment]
不支持，要做单 Activity 应用 Fragment 之间的跳转 可以用 JetPack 的 `navigation`
