### ISSUE TITLE
AGP 升级到8.5  java 升级到 17 根本跑不起来 

### ISSUE THREAD

**Issue by fengxin0210fx** [aleyn97/router#11]
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:9: 错误: 无法访问BaseActivity
import com.aleyn.lib_base.BaseActivity;
                         ^
  错误的类文件: E:\softwork\code\as\demo\router\lib_base\build\intermediates\compile_library_classes_jar\debug\bundleLibCompileToJarDebug\classes.jar(/com/aleyn/lib_base/BaseActivity.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:10: 错误: 无法访问UserData
import com.aleyn.lib_base.pojo.UserData;
                              ^
  错误的类文件: E:\softwork\code\as\demo\router\lib_base\build\intermediates\compile_library_classes_jar\debug\bundleLibCompileToJarDebug\classes.jar(/com/aleyn/lib_base/pojo/UserData.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:11: 错误: 无法访问IMainProvider
import com.aleyn.lib_base.provider.IMainProvider;
                                  ^
  错误的类文件: E:\softwork\code\as\demo\router\lib_base\build\intermediates\compile_library_classes_jar\debug\bundleLibCompileToJarDebug\classes.jar(/com/aleyn/lib_base/provider/IMainProvider.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:19: 错误: 找不到符号
public class TwoActivity extends BaseActivity {
                                 ^
  符号: 类 BaseActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:30: 错误: 找不到符号
    UserData userData;
    ^
  符号:   类 UserData
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:33: 错误: 找不到符号
    IMainProvider roomProvider;
    ^
  符号:   类 IMainProvider
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:36: 错误: 找不到符号
    IMainProvider roomProvider2;
    ^
  符号:   类 IMainProvider
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:38: 错误: 找不到符号
    IMainProvider roomProvider3 = LRouter.getByJava(IMainProvider.class, new StringQualifier("main2"));
    ^
  符号:   类 IMainProvider
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:38: 错误: 找不到符号
    IMainProvider roomProvider3 = LRouter.getByJava(IMainProvider.class, new StringQualifier("main2"));
                                                    ^
  符号:   类 IMainProvider
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:41: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:43: 错误: 找不到符号
        super.onCreate(savedInstanceState);
        ^
  符号:   变量 super
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:44: 错误: 找不到符号
        setContentView(R.layout.activity_two);
        ^
  符号:   方法 setContentView(int)
  位置: 类 TwoActivity
E:\softwork\code\as\demo\router\module_two\src\main\java\com\aleyn\module_two\TwoActivity.java:46: 错误: 找不到符号
        TextView tvInfo = findViewById(R.id.tv_info);
                          ^
  符号:   方法 findViewById(int)
  位置: 类 TwoActivity

**Comment by aleyn97** [comment]
Demo 是用的 JDK 11，如果用高版本（JDK 17）打包发布，就不会像下兼容。使用 JDK 11 的项目就集成不了了。

目前公司项目  AGP 8.7 加 JDK 17  没任何问题的
