### ISSUE TITLE
你为什么不考虑是直接无缝迁移到你的LRouter呢

### ISSUE THREAD

**Issue by lianyagang** [aleyn97/router#2]
代码写的很好。基于我个人来说。从Arouter 迁移到Lrouter，成本还真的不低。例如IProvider呢？初始化的方式，调用的方式。建议尽量考虑是无缝切换

**Comment by aleyn97** [comment]
感谢提的建议。写之前有考虑过无缝切换，由于是全部重构的，ARouter 有些功能有更好的实现方式。最终还是放弃了。

最近准备写个 Task 任务 可以直接 一键 迁移。

**Comment by aleyn97** [comment]
> > 感谢提的建议。写之前有考虑过无缝切换，由于是全部重构的，ARouter 有些功能有更好的实现方式。最终还是放弃了。
> > 最近准备写个 Task 任务 可以直接 一键 迁移。
> 
> 如果是这样。那你可以考虑下。把文档完善下。之前ARouter的写法，如何换成你现在的写法。这样迁移的时候，成本比较低。

OK，有需要的话我会另写一篇单独的迁移文章，链接放 README 里边。

**Comment by aleyn97** [comment]
https://github.com/aleyn97/router/wiki/ARouter-%E8%BF%81%E7%A7%BB%E5%88%B0-LRouter

> > > 感谢提的建议。写之前有考虑过无缝切换，由于是全部重构的，ARouter 有些功能有更好的实现方式。最终还是放弃了。
> > > 最近准备写个 Task 任务 可以直接 一键 迁移。
> > 
> > 
> > 如果是这样。那你可以考虑下。把文档完善下。之前ARouter的写法，如何换成你现在的写法。这样迁移的时候，成本比较低。
> 
> OK，有需要的话我会另写一篇单独的迁移文章，链接放 README 里边。

https://github.com/aleyn97/router/wiki/ARouter-%E8%BF%81%E7%A7%BB%E5%88%B0-LRouter
