### ISSUE TITLE
enterAnim 和 exitAnim 默认值都是 builder 里面的 -1 导致覆盖系统的默认动画

### ISSUE THREAD

**Issue by xiaoyvyv** [aleyn97/router#4]
https://github.com/aleyn97/router/blob/bb228d08cb74420b3874e26d23f5a94abecd520c/router/src/main/java/com/aleyn/router/core/Navigator.kt#L127-L129

### 这里有错误
`enterAnim` 和 `exitAnim` 默认值都是 `builder` 里面的 `-1`，这里没有判断为 `-1` 时跳过，然后会覆盖系统的默认动画。

**Comment by xiaoyvyv** [comment]
这里应该改成

**Comment by aleyn97** [comment]
> 这里应该改成
> 
> ```kotlin
> if ((enterAnim != -1 || exitAnim != -1) && currentContext is Activity) { 
>      currentContext.overridePendingTransition(enterAnim, exitAnim) 
>  } 
> ```
> 
> 因为有时候会手动设置取消转场动画会设置为0，不应该跳过

嗯嗯，上午看到你提的 另一个 Issues  我也发现了。Navigator.Builder 的第二个构造函数也少了  exitAnim 的赋值。晚上有时间的话我发个修复版

**Comment by aleyn97** [comment]
[v1.0.4](https://github.com/aleyn97/router/releases/tag/1.0.4)
