### ISSUE TITLE
能否在迁移说明里面添加下新的混淆配置

### ISSUE THREAD

**Issue by lanbejick** [aleyn97/router#5]
找了下proguard没有写

**Comment by aleyn97** [comment]
> 找了下proguard没有写

现在不需要添加额外混淆的，要保留的地方已经加了 `@Keep ` 注解了。如果混淆后遇到问题可以提 Issues

**Comment by lanbejick** [comment]
> > 找了下proguard没有写
> 
> 现在不需要添加额外的混乱，要保留已经添加`@Keep `注释的位置。如果以后遇到问题可能会提出问题

好的，谢谢
