### ISSUE TITLE
有办法优化一下编译流程吗？目前即使未修改任何代码，每次运行 dexBuilderDebug 都会耗时很久

### ISSUE THREAD

**Issue by xiaoyvyv** [aleyn97/router#6]
项目目前每次运行都会耗时将近一分钟（即使不修改代码的情况下），都做了全量的classes处理，能优化一下吗？

![图片](https://github.com/aleyn97/router/assets/29088158/da2b6878-8a69-4623-8f3b-2e8dff54a850)
![图片](https://github.com/aleyn97/router/assets/29088158/a45efd9f-255a-4c43-aafc-05ed1ec6540f)

**Comment by aleyn97** [comment]
> 项目目前每次运行都会耗时将近一分钟（即使不修改代码的情况下），都做了全量的classes处理，能优化一下吗？
> 
> ![图片](https://user-images.githubusercontent.com/29088158/284228243-da2b6878-8a69-4623-8f3b-2e8dff54a850.png) ![图片](https://user-images.githubusercontent.com/29088158/284228684-a45efd9f-255a-4c43-aafc-05ed1ec6540f.png)

已经在寻找方案了， `AsmClassVisitorFactory` 无法满足现在的需求，不得已才用的自定义 TASK 全量处理。

**Comment by xiaoyvyv** [comment]
Hi，请问这个有解决方案了吗？

**Comment by xiaoyvyv** [comment]
最近Fork仓库大致看了一下，发现了耗时的原因

因为你扫描修改插桩的类是在你的 router 模块下，这个是作为依赖到项目的，所以你 toTransform 只能设置 Scope 为 ALL，这样将会导致很严重的耗时。因为公司项目一般很大，依赖将非常多，全量扫描的生成的 classes.jar 能达到 100M+，这里有很大的优化空间。

### 优化方案：
1. 将 toTransform 的 Scope 设置为 PROJECT
2. 由于 Scope 设置为 PROJECT 仅处理项目内的 class，将无法修改依赖的相关 jar 的类，所以需要调整一下。将 router 模块内的插桩类中的的几个初始化方法抽象出来，比如 IRouterGenerate

```kotlin
@Keep
interface IRouterGenerate {
    @Keep
    fun injectAutowired(target: Any?)

    @Keep
    fun initModuleRouter()

    @Keep
    fun registerIntercept()

    @Keep
    fun registerAllInitializer()
}
```
然后由插件再 app 模块生成一个位于 generated 目录下的占位插桩类 `RouterGenerateHolder`，然后继承 `IRouterGenerate`，这个类属于 PROJECT 范围内，可以被扫描到并修改。

```kotlin
androidComponents.onVariants { variant ->
            if (isApp) {
                val addSourceTaskProvider = project.tasks.register(
                    "${variant.name}RouterStubClass",
                    RouterStubClassTask::class.java
                )

                @Suppress("UnstableApiUsage")
                variant.sources.java!!.addGeneratedSourceDirectory(
                    addSourceTaskProvider,
                    RouterStubClassTask::outputFolder
                )
            }
}
```

3. 然后 router 模块内 LRouterGenerate.kt 相关的方法，直接去加载 RouterGenerateHolder 的单例，并调用对应方法即可。

```kotlin
package com.aleyn.router.inject

import androidx.annotation.Keep

private val instance: IRouterGenerate by lazy {
    Class.forName("com.router.RouterGenerateHolder")
        .getDeclaredConstructor()
        .newInstance() as IRouterGenerate
}

@Keep
internal fun injectAutowired(target: Any?) {
    instance.injectAutowired(target)
}

@Keep
internal fun initModuleRouter() {
    instance.initModuleRouter()
}

@Keep
internal fun registerIntercept() {
    instance.registerIntercept()
}

@Keep
internal fun registerAllInitializer() {
    instance.registerAllInitializer()
}
```
4. 还有一点，由于 toTransform 设置 Scope 为 PROJECT，还需要修改 `LRouterClassTask` 的注入，需要所有 application 和 library 模块都要启用，不单只是 application 模块。

基本上就可以大幅优化编译时间了

**Comment by xiaoyvyv** [comment]
可以看下我 fork 后优化的 [commit](https://github.com/xiaoyvyv/LRouter/commit/b6c894517aad71b5c8c32619875d1a32d52201cf#diff-e70f2d50712f1ed0bfd6cdfcb5924ccc254cc2c27fe6ba3415a080e6a215a9bc)

**Comment by aleyn97** [comment]
@xiaoyvyv 不好意思，过了年这段时间一直在忙，你的方案我看了，最开始其实考虑过在APP模块下做插入，当时为了尽量的减少反射，放到 Router 模块了，现在确实太影响编译速度了，我把你修改的，整理下先发个版本出来。

然后我试着用  `transformClassesWith`  方式处理编译速度会更快，会直接走增量更新。有一点问题就是 APP 主模块下不能写与LRouter 相关的类文件，全都要放到子模块，等我再想办法把这个问题解决了，再发布 `transformClassesWith` 方式。

**Comment by aleyn97** [comment]
@xiaoyvyv  可以试下 [1.0.6](https://github.com/aleyn97/router/releases/tag/1.0.6)
