### ISSUE TITLE
无法传递Parcelable嵌套，@Autowired不能注解内部子类，编译时报错

### ISSUE THREAD

**Issue by CallMeLyric** [aleyn97/router#7]
![image](https://github.com/aleyn97/router/assets/22878603/1bd59dac-e0d3-4720-91e8-5365ae5cc7ae)
![image](https://github.com/aleyn97/router/assets/22878603/903e5f97-114d-4164-bc2f-e038398e47c9)

**Comment by CallMeLyric** [comment]
Parcelable数据传递失败是因为我没写默认值也不能为null。。。。

**Comment by aleyn97** [comment]
> ![image](https://private-user-images.githubusercontent.com/22878603/288012376-1bd59dac-e0d3-4720-91e8-5365ae5cc7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzA3NDUsIm5iZiI6MTcwMTgzMDQ0NSwicGF0aCI6Ii8yMjg3ODYwMy8yODgwMTIzNzYtMWJkNTlkYWMtZTBkMy00NzIwLTkxZTgtNTM2NWFlNWNjN2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAyNDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNjMzY2E2ODU3N2I3OGFmZWFmMTU0NWFkMDQwZDEyMzNhOWU5OTAyODk3ZTFiOGE2YWUwZDcwZDU3ZjQ5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Da_EnXZhufr-U16Q-SXHZTWVTi9KrXu0tCyjqr_U9g) ![image](https://private-user-images.githubusercontent.com/22878603/288012456-903e5f97-114d-4164-bc2f-e038398e47c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzA3NDUsIm5iZiI6MTcwMTgzMDQ0NSwicGF0aCI6Ii8yMjg3ODYwMy8yODgwMTI0NTYtOTAzZTVmOTctMTE0ZC00MTY0LWJjMmYtZTAzODM5OGU0N2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAyNDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjFjNmM0MzgzMmI1OTYwZWIwZDI4NGIxNzMzODU2YzkyMjI1MzhmNjQ4MzdjZjE1M2JkMWJlZTYxNTk0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5_gqz-Fv4pawq3TUdhgFAQTxGkCVhqZpbNi1_EQb-kY)

生成模板类导包的问题，问题会记录下来，下版本解决。你可以先不写成内部类，写在同一个文件平行一下，如下：

```kotlin
@Parcelize
data class RpUserInfo(
    val tag: Tag
) : Parcelable

@Parcelize
data class Tag(
    val name: String
) : Parcelable
```
