### ISSUE TITLE
property 'moduleName' because it has no value available.

### ISSUE THREAD

**Issue by qiushihang** [aleyn97/router#9]
> Could not create task ':station_home:kspDebugUnitTestKotlin'.
   > Cannot query the value of task ':station_home:compileDebugUnitTestKotlin' property 'moduleName' because it has no value available.

我使用了你的框架，报错，求助怎么解

**Comment by aleyn97** [comment]
> > Could not create task ':station_home:kspDebugUnitTestKotlin'.
> > Cannot query the value of task ':station_home:compileDebugUnitTestKotlin' property 'moduleName' because it has no value available.
> 
> 我使用了你的框架，报错，求助怎么解

每个模块的 build.gradle 都要 加 `apply plugin: 'aleyn-router'` 这个插件的
